# Generated by Django 3.0.7 on 2020-06-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('extracted_data', models.TextField(blank=True, default=None)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
