# Generated by Django 3.0.7 on 2020-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_visiblity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visiblity',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1, max_length=1),
        ),
    ]
