# Generated by Django 3.0.7 on 2020-06-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200625_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1),
        ),
    ]
