# Generated by Django 3.0.7 on 2020-06-26 17:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200625_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='extracted_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
    ]
